//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Препарат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Препарат()
        {
            this.Прием_пациента = new HashSet<Прием_пациента>();
        }
    
        public int Код_препарата { get; set; }
        public string Название { get; set; }
        public Nullable<double> Дозировка { get; set; }
        public string Ед_измерения_дозировки { get; set; }
        public string Форма_выпуска { get; set; }
        public Nullable<System.DateTime> Срок_годности { get; set; }
        public string Серия { get; set; }
        public Nullable<int> Код_производителя { get; set; }
    
        public virtual Производитель Производитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Прием_пациента> Прием_пациента { get; set; }
    }
}
