//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Участок
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Участок()
        {
            this.Пациент = new HashSet<Пациент>();
        }
    
        public int Номер_участка { get; set; }
        public int Код_участкового_врача { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациент> Пациент { get; set; }
        public virtual Участковый_врач Участковый_врач { get; set; }
    }
}
